/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.zylklab.flink.sandbox.broadcaststate.pojo;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Event extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7168254477785600220L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"net.zylklab.flink.sandbox.broadcaststate.pojo\",\"fields\":[{\"name\":\"var_id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"var_name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"value\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"ts\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Event> ENCODER =
      new BinaryMessageEncoder<Event>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Event> DECODER =
      new BinaryMessageDecoder<Event>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Event> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Event> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Event> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Event>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Event to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Event from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Event instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Event fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String var_id;
  @Deprecated public java.lang.String var_name;
  @Deprecated public java.lang.Double value;
  @Deprecated public java.lang.Long ts;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Event() {}

  /**
   * All-args constructor.
   * @param var_id The new value for var_id
   * @param var_name The new value for var_name
   * @param value The new value for value
   * @param ts The new value for ts
   */
  public Event(java.lang.String var_id, java.lang.String var_name, java.lang.Double value, java.lang.Long ts) {
    this.var_id = var_id;
    this.var_name = var_name;
    this.value = value;
    this.ts = ts;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return var_id;
    case 1: return var_name;
    case 2: return value;
    case 3: return ts;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: var_id = (java.lang.String)value$; break;
    case 1: var_name = (java.lang.String)value$; break;
    case 2: value = (java.lang.Double)value$; break;
    case 3: ts = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'var_id' field.
   * @return The value of the 'var_id' field.
   */
  public java.lang.String getVarId() {
    return var_id;
  }


  /**
   * Sets the value of the 'var_id' field.
   * @param value the value to set.
   */
  public void setVarId(java.lang.String value) {
    this.var_id = value;
  }

  /**
   * Gets the value of the 'var_name' field.
   * @return The value of the 'var_name' field.
   */
  public java.lang.String getVarName() {
    return var_name;
  }


  /**
   * Sets the value of the 'var_name' field.
   * @param value the value to set.
   */
  public void setVarName(java.lang.String value) {
    this.var_name = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.Double getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.Double value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'ts' field.
   * @return The value of the 'ts' field.
   */
  public java.lang.Long getTs() {
    return ts;
  }


  /**
   * Sets the value of the 'ts' field.
   * @param value the value to set.
   */
  public void setTs(java.lang.Long value) {
    this.ts = value;
  }

  /**
   * Creates a new Event RecordBuilder.
   * @return A new Event RecordBuilder
   */
  public static net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder newBuilder() {
    return new net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder();
  }

  /**
   * Creates a new Event RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Event RecordBuilder
   */
  public static net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder newBuilder(net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder other) {
    if (other == null) {
      return new net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder();
    } else {
      return new net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder(other);
    }
  }

  /**
   * Creates a new Event RecordBuilder by copying an existing Event instance.
   * @param other The existing instance to copy.
   * @return A new Event RecordBuilder
   */
  public static net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder newBuilder(net.zylklab.flink.sandbox.broadcaststate.pojo.Event other) {
    if (other == null) {
      return new net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder();
    } else {
      return new net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder(other);
    }
  }

  /**
   * RecordBuilder for Event instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Event>
    implements org.apache.avro.data.RecordBuilder<Event> {

    private java.lang.String var_id;
    private java.lang.String var_name;
    private java.lang.Double value;
    private java.lang.Long ts;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.var_id)) {
        this.var_id = data().deepCopy(fields()[0].schema(), other.var_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.var_name)) {
        this.var_name = data().deepCopy(fields()[1].schema(), other.var_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.value)) {
        this.value = data().deepCopy(fields()[2].schema(), other.value);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.ts)) {
        this.ts = data().deepCopy(fields()[3].schema(), other.ts);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Event instance
     * @param other The existing instance to copy.
     */
    private Builder(net.zylklab.flink.sandbox.broadcaststate.pojo.Event other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.var_id)) {
        this.var_id = data().deepCopy(fields()[0].schema(), other.var_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.var_name)) {
        this.var_name = data().deepCopy(fields()[1].schema(), other.var_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.value)) {
        this.value = data().deepCopy(fields()[2].schema(), other.value);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ts)) {
        this.ts = data().deepCopy(fields()[3].schema(), other.ts);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'var_id' field.
      * @return The value.
      */
    public java.lang.String getVarId() {
      return var_id;
    }


    /**
      * Sets the value of the 'var_id' field.
      * @param value The value of 'var_id'.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder setVarId(java.lang.String value) {
      validate(fields()[0], value);
      this.var_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'var_id' field has been set.
      * @return True if the 'var_id' field has been set, false otherwise.
      */
    public boolean hasVarId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'var_id' field.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder clearVarId() {
      var_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'var_name' field.
      * @return The value.
      */
    public java.lang.String getVarName() {
      return var_name;
    }


    /**
      * Sets the value of the 'var_name' field.
      * @param value The value of 'var_name'.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder setVarName(java.lang.String value) {
      validate(fields()[1], value);
      this.var_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'var_name' field has been set.
      * @return True if the 'var_name' field has been set, false otherwise.
      */
    public boolean hasVarName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'var_name' field.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder clearVarName() {
      var_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.Double getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder setValue(java.lang.Double value) {
      validate(fields()[2], value);
      this.value = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder clearValue() {
      value = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ts' field.
      * @return The value.
      */
    public java.lang.Long getTs() {
      return ts;
    }


    /**
      * Sets the value of the 'ts' field.
      * @param value The value of 'ts'.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder setTs(java.lang.Long value) {
      validate(fields()[3], value);
      this.ts = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ts' field has been set.
      * @return True if the 'ts' field has been set, false otherwise.
      */
    public boolean hasTs() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ts' field.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Event.Builder clearTs() {
      ts = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Event build() {
      try {
        Event record = new Event();
        record.var_id = fieldSetFlags()[0] ? this.var_id : (java.lang.String) defaultValue(fields()[0]);
        record.var_name = fieldSetFlags()[1] ? this.var_name : (java.lang.String) defaultValue(fields()[1]);
        record.value = fieldSetFlags()[2] ? this.value : (java.lang.Double) defaultValue(fields()[2]);
        record.ts = fieldSetFlags()[3] ? this.ts : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Event>
    WRITER$ = (org.apache.avro.io.DatumWriter<Event>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Event>
    READER$ = (org.apache.avro.io.DatumReader<Event>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.var_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.var_id);
    }

    if (this.var_name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.var_name);
    }

    if (this.value == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.value);
    }

    if (this.ts == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.ts);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.var_id = null;
      } else {
        this.var_id = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.var_name = null;
      } else {
        this.var_name = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.value = null;
      } else {
        this.value = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.ts = null;
      } else {
        this.ts = in.readLong();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.var_id = null;
          } else {
            this.var_id = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.var_name = null;
          } else {
            this.var_name = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.value = null;
          } else {
            this.value = in.readDouble();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ts = null;
          } else {
            this.ts = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










