/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.zylklab.flink.sandbox.broadcaststate.pojo;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Limit extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9102671915116870785L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Limit\",\"namespace\":\"net.zylklab.flink.sandbox.broadcaststate.pojo\",\"fields\":[{\"name\":\"var_id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"var_name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"max_limit\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"min_limit\",\"type\":[\"null\",\"double\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Limit> ENCODER =
      new BinaryMessageEncoder<Limit>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Limit> DECODER =
      new BinaryMessageDecoder<Limit>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Limit> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Limit> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Limit> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Limit>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Limit to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Limit from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Limit instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Limit fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String var_id;
  @Deprecated public java.lang.String var_name;
  @Deprecated public java.lang.Double max_limit;
  @Deprecated public java.lang.Double min_limit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Limit() {}

  /**
   * All-args constructor.
   * @param var_id The new value for var_id
   * @param var_name The new value for var_name
   * @param max_limit The new value for max_limit
   * @param min_limit The new value for min_limit
   */
  public Limit(java.lang.String var_id, java.lang.String var_name, java.lang.Double max_limit, java.lang.Double min_limit) {
    this.var_id = var_id;
    this.var_name = var_name;
    this.max_limit = max_limit;
    this.min_limit = min_limit;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return var_id;
    case 1: return var_name;
    case 2: return max_limit;
    case 3: return min_limit;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: var_id = (java.lang.String)value$; break;
    case 1: var_name = (java.lang.String)value$; break;
    case 2: max_limit = (java.lang.Double)value$; break;
    case 3: min_limit = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'var_id' field.
   * @return The value of the 'var_id' field.
   */
  public java.lang.String getVarId() {
    return var_id;
  }


  /**
   * Sets the value of the 'var_id' field.
   * @param value the value to set.
   */
  public void setVarId(java.lang.String value) {
    this.var_id = value;
  }

  /**
   * Gets the value of the 'var_name' field.
   * @return The value of the 'var_name' field.
   */
  public java.lang.String getVarName() {
    return var_name;
  }


  /**
   * Sets the value of the 'var_name' field.
   * @param value the value to set.
   */
  public void setVarName(java.lang.String value) {
    this.var_name = value;
  }

  /**
   * Gets the value of the 'max_limit' field.
   * @return The value of the 'max_limit' field.
   */
  public java.lang.Double getMaxLimit() {
    return max_limit;
  }


  /**
   * Sets the value of the 'max_limit' field.
   * @param value the value to set.
   */
  public void setMaxLimit(java.lang.Double value) {
    this.max_limit = value;
  }

  /**
   * Gets the value of the 'min_limit' field.
   * @return The value of the 'min_limit' field.
   */
  public java.lang.Double getMinLimit() {
    return min_limit;
  }


  /**
   * Sets the value of the 'min_limit' field.
   * @param value the value to set.
   */
  public void setMinLimit(java.lang.Double value) {
    this.min_limit = value;
  }

  /**
   * Creates a new Limit RecordBuilder.
   * @return A new Limit RecordBuilder
   */
  public static net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder newBuilder() {
    return new net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder();
  }

  /**
   * Creates a new Limit RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Limit RecordBuilder
   */
  public static net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder newBuilder(net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder other) {
    if (other == null) {
      return new net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder();
    } else {
      return new net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder(other);
    }
  }

  /**
   * Creates a new Limit RecordBuilder by copying an existing Limit instance.
   * @param other The existing instance to copy.
   * @return A new Limit RecordBuilder
   */
  public static net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder newBuilder(net.zylklab.flink.sandbox.broadcaststate.pojo.Limit other) {
    if (other == null) {
      return new net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder();
    } else {
      return new net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder(other);
    }
  }

  /**
   * RecordBuilder for Limit instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Limit>
    implements org.apache.avro.data.RecordBuilder<Limit> {

    private java.lang.String var_id;
    private java.lang.String var_name;
    private java.lang.Double max_limit;
    private java.lang.Double min_limit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.var_id)) {
        this.var_id = data().deepCopy(fields()[0].schema(), other.var_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.var_name)) {
        this.var_name = data().deepCopy(fields()[1].schema(), other.var_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.max_limit)) {
        this.max_limit = data().deepCopy(fields()[2].schema(), other.max_limit);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.min_limit)) {
        this.min_limit = data().deepCopy(fields()[3].schema(), other.min_limit);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Limit instance
     * @param other The existing instance to copy.
     */
    private Builder(net.zylklab.flink.sandbox.broadcaststate.pojo.Limit other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.var_id)) {
        this.var_id = data().deepCopy(fields()[0].schema(), other.var_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.var_name)) {
        this.var_name = data().deepCopy(fields()[1].schema(), other.var_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.max_limit)) {
        this.max_limit = data().deepCopy(fields()[2].schema(), other.max_limit);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.min_limit)) {
        this.min_limit = data().deepCopy(fields()[3].schema(), other.min_limit);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'var_id' field.
      * @return The value.
      */
    public java.lang.String getVarId() {
      return var_id;
    }


    /**
      * Sets the value of the 'var_id' field.
      * @param value The value of 'var_id'.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder setVarId(java.lang.String value) {
      validate(fields()[0], value);
      this.var_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'var_id' field has been set.
      * @return True if the 'var_id' field has been set, false otherwise.
      */
    public boolean hasVarId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'var_id' field.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder clearVarId() {
      var_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'var_name' field.
      * @return The value.
      */
    public java.lang.String getVarName() {
      return var_name;
    }


    /**
      * Sets the value of the 'var_name' field.
      * @param value The value of 'var_name'.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder setVarName(java.lang.String value) {
      validate(fields()[1], value);
      this.var_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'var_name' field has been set.
      * @return True if the 'var_name' field has been set, false otherwise.
      */
    public boolean hasVarName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'var_name' field.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder clearVarName() {
      var_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'max_limit' field.
      * @return The value.
      */
    public java.lang.Double getMaxLimit() {
      return max_limit;
    }


    /**
      * Sets the value of the 'max_limit' field.
      * @param value The value of 'max_limit'.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder setMaxLimit(java.lang.Double value) {
      validate(fields()[2], value);
      this.max_limit = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'max_limit' field has been set.
      * @return True if the 'max_limit' field has been set, false otherwise.
      */
    public boolean hasMaxLimit() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'max_limit' field.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder clearMaxLimit() {
      max_limit = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'min_limit' field.
      * @return The value.
      */
    public java.lang.Double getMinLimit() {
      return min_limit;
    }


    /**
      * Sets the value of the 'min_limit' field.
      * @param value The value of 'min_limit'.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder setMinLimit(java.lang.Double value) {
      validate(fields()[3], value);
      this.min_limit = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'min_limit' field has been set.
      * @return True if the 'min_limit' field has been set, false otherwise.
      */
    public boolean hasMinLimit() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'min_limit' field.
      * @return This builder.
      */
    public net.zylklab.flink.sandbox.broadcaststate.pojo.Limit.Builder clearMinLimit() {
      min_limit = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Limit build() {
      try {
        Limit record = new Limit();
        record.var_id = fieldSetFlags()[0] ? this.var_id : (java.lang.String) defaultValue(fields()[0]);
        record.var_name = fieldSetFlags()[1] ? this.var_name : (java.lang.String) defaultValue(fields()[1]);
        record.max_limit = fieldSetFlags()[2] ? this.max_limit : (java.lang.Double) defaultValue(fields()[2]);
        record.min_limit = fieldSetFlags()[3] ? this.min_limit : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Limit>
    WRITER$ = (org.apache.avro.io.DatumWriter<Limit>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Limit>
    READER$ = (org.apache.avro.io.DatumReader<Limit>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.var_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.var_id);
    }

    if (this.var_name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.var_name);
    }

    if (this.max_limit == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.max_limit);
    }

    if (this.min_limit == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.min_limit);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.var_id = null;
      } else {
        this.var_id = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.var_name = null;
      } else {
        this.var_name = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.max_limit = null;
      } else {
        this.max_limit = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.min_limit = null;
      } else {
        this.min_limit = in.readDouble();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.var_id = null;
          } else {
            this.var_id = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.var_name = null;
          } else {
            this.var_name = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.max_limit = null;
          } else {
            this.max_limit = in.readDouble();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.min_limit = null;
          } else {
            this.min_limit = in.readDouble();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










